import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import Footer from "./_components/footer";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import Navbar from "./_components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html className="h-full" lang="en">
        <body className={`h-full ${inter.className}`}>
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
